"""
PDF Report Service — Section 11.3.
Renders the Jinja2 HTML template into a PDF on demand (not pre-generated
or stored — keeps things simple, per the roadmap's Day 6 scope).

Uses xhtml2pdf instead of WeasyPrint: xhtml2pdf is pure-Python (built on
ReportLab) and needs no system-level GTK/Pango libraries, which are
notoriously painful to set up correctly on Windows.
"""
from datetime import datetime
from io import BytesIO
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
from xhtml2pdf import pisa

from app.api.categories import CATEGORIES

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"
env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)))

CATEGORY_LOOKUP = {c["code"]: c for c in CATEGORIES}


def _category_label(category_code: str | None, lang: str) -> str | None:
    if not category_code:
        return None
    entry = CATEGORY_LOOKUP.get(category_code)
    if not entry:
        return category_code  # unknown code — show raw value rather than hide it
    return entry["label_de"] if lang == "de" else entry["label_en"]

LABELS = {
    "en": {
        "session_ref": "Session Ref",
        "patient_info": "Patient Information",
        "name": "Name",
        "age": "Age",
        "blood_group": "Blood Group",
        "category": "Category",
        "assessment_result": "Assessment Result",
        "matched_against": "Matched Against (Reference Conditions)",
        "recommended_action": "Recommended Action",
        "visual_observation": "AI Visual Observation",
        "not_a_diagnosis": "Not a diagnosis — general observation only.",
        "disclaimer": (
            "This report is generated by an AI decision-support tool. It is not a "
            "medical diagnosis. Please consult a licensed healthcare professional."
        ),
    },
    "de": {
        "session_ref": "Sitzungs-Ref",
        "patient_info": "Patienteninformationen",
        "name": "Name",
        "age": "Alter",
        "blood_group": "Blutgruppe",
        "category": "Kategorie",
        "assessment_result": "Bewertungsergebnis",
        "matched_against": "Abgeglichen mit (Referenzerkrankungen)",
        "recommended_action": "Empfohlene Maßnahme",
        "visual_observation": "KI-Sichtbeobachtung",
        "not_a_diagnosis": "Keine Diagnose — nur eine allgemeine Beobachtung.",
        "disclaimer": (
            "Dieser Bericht wird von einem KI-Entscheidungsunterstützungstool erstellt. "
            "Es handelt sich nicht um eine medizinische Diagnose. Bitte konsultieren Sie "
            "einen zugelassenen Arzt."
        ),
    },
}

SEVERITY_LABELS = {
    "en": {"EMERGENCY": "Emergency", "URGENT": "Urgent", "ROUTINE": "Routine", "SELF_CARE": "Self-care"},
    "de": {"EMERGENCY": "Notfall", "URGENT": "Dringend", "ROUTINE": "Routine", "SELF_CARE": "Selbstpflege"},
}


def generate_triage_report_pdf(session, lang: str = "en", visual_observation: dict | None = None) -> bytes:
    """
    session: a TriageSession model instance (already committed/refreshed).
    Returns raw PDF bytes — caller streams these back as the response body.
    """
    lang = lang if lang in LABELS else "en"
    labels = LABELS[lang]

    template = env.get_template("report_template.html")
    html_content = template.render(
        app_name="Clinical Triage Assistant",
        report_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        session_id_short=str(session.id)[:8],
        session_id_full=str(session.id),
        patient_name=session.patient_name,
        patient_age=session.patient_age,
        patient_blood_group=session.patient_blood_group,
        category=_category_label(session.category, lang),
        severity=session.severity_result or "ROUTINE",
        severity_label=SEVERITY_LABELS.get(lang, SEVERITY_LABELS["en"]).get(
            session.severity_result or "ROUTINE", session.severity_result
        ),
        reasoning=session.ai_reasoning,
        cited_conditions=session.cited_conditions or [],
        recommended_action=session.recommended_action,
        visual_observation=visual_observation,
        labels=labels,
    )

    output = BytesIO()
    result = pisa.CreatePDF(src=html_content, dest=output)
    if result.err:
        raise RuntimeError(f"xhtml2pdf failed to render PDF (err code {result.err})")

    return output.getvalue()
